# Generated by Django 4.1.5 on 2023-02-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Beef', 'Beef'), ('Breakfast', 'Breakfast'), ('Chicken', 'Chicken'), ('Dessert', 'Dessert'), ('Goat', 'Goat'), ('Lamb', 'Lamb'), ('Miscellaneous', 'Miscellaneous'), ('Pasta', 'Pasta'), ('Pork', 'Pork'), ('Seafood', 'Seafood'), ('Side', 'Side'), ('Starter', 'Starter'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')], max_length=16)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
