# Generated by Django 4.1.5 on 2023-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_alter_dish_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishproduct',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
