# Generated by Django 4.1.5 on 2023-02-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_measurement'),
        ('dishes', '0005_alter_dishproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishproduct',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dishes.dish'),
        ),
        migrations.AlterField(
            model_name='dishproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='products.product'),
        ),
    ]
