# Generated by Django 4.1.5 on 2023-02-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_userproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='products.product'),
        ),
    ]
